music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'

urlpatterns = [
    #Front URL
    url(r'^$', views.index, name='index'),

    #User URLS
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    #Album URLS
    url(r'^(?P<pk>[0-9]+)/$',views.album_view, name='detail'),
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.delete_album, name='album-delete'),
   	url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),

    #Song URLS
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<album_id>[0-9]+)/favorite_song/(?P<song_id>[0-9]+)/$', views.favorite, name='favorite'),
   	url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
   	url(r'^(?P<album_id>[0-9]+)/play_song/(?P<song_id>[0-9]+)/$', views.play_song, name='play_song'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
   	]

website/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	

music/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.FileField()
	is_favorite = models.BooleanField(default=False)

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk': self.pk})

	def __str__ (self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model): 
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)
	song_file = models.FileField()

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk': self.album})
	
	def __str__ (self):
		return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Song

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	
	class Meta:
		model = User
		fields = ['username', 'password' ,'first_name', 'last_name', 'email' ]

class SongForm(forms.ModelForm):

	class Meta:
		model = Song
		fields = ['song_title','song_file']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.core.urlresolvers import reverse_lazy
from .models import Album, Song
from .forms import UserForm, SongForm
from django.http import JsonResponse
from django.db.models import Q


AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']


#Front Page
def index(request):
    if not request.user.is_authenticated():
        username = None
    else: username = request.user.get_short_name()
    albums = Album.objects.all()
    song_results = Song.objects.all()
    query = request.GET.get("q")
    if query:
        albums = albums.filter(
            Q(album_title__icontains=query) |
            Q(artist__icontains=query) | Q(genre__icontains=query)
        ).distinct()
        song_results = song_results.filter(
            Q(song_title__icontains=query)
        ).distinct()
        return render(request, 'music/index.html', {
            'all_albums': albums,
            'songs': song_results,
            'username' : username,
        })
    else:
        return render(request, 'music/index.html', {'all_albums': albums,
            'username' : username, })


#Album Stuff
def album_view(request, pk):
    album = Album.objects.get(id=pk)
    if not request.user.is_authenticated(): username = None
    else: username = request.user.get_short_name()
    return render(request, 'music/detail.html', {'username': username, 
        'album': album})

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')

def delete_album(request,pk):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html', {'error_message': 
            'Need to Login'} )
    elif not request.user.is_staff: 
        return render(request, 'music/login.html', {'error_message': 
            'Only Admin can delete Album'} )
    else:
        album = get_object_or_404(Album, pk=pk)
        album.delete()
        return redirect('music:index')

def favorite_album(request, album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html', {'error_message': 
            'Need to Login'} )
    if request.method == "GET":
        album = get_object_or_404(Album, pk=album_id)
        try:
            if album.is_favorite:
                album.is_favorite = False
            else:
                album.is_favorite = True
            album.save()
        except (KeyError, Album.DoesNotExist):
            return JsonResponse({'success': False})
        else:
            return redirect('music:index')


#User Stuff

class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'

	def get(self, request):
		form= self.form_class(None)
		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form= self.form_class(request.POST) 

		if form.is_valid():

			user = form.save(commit=False)

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			user = authenticate(username=username, password=password)

			if user is not None:

				if user.is_active:
					login(request, user)
					request.user
					return redirect('music:index')

		else :
			return render(request, self.template_name, {'form': form})

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None :
            if user.is_active:
                login(request, user)
                albums = Album.objects.all()
                username = user.get_short_name() 
                return redirect('music:index')
            elif user.is_authenticated():
                return render(request, 'music/login.html', {'error_message': 
                    'Your are alrady loggedin'})
            else:
                return render(request, 'music/login.html', {'error_message': 
                    'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 
                'Invalid login'})
    return render(request, 'music/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


#Song Stuff

def create_song(request, album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html', {'error_message': 
            'Need to Login First'})
    else: 
        username = request.user.get_short_name()
        form = SongForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(Album, pk=album_id)
        if form.is_valid():
            albums_songs = album.song_set.all()
            for s in albums_songs:
                if s.song_title == form.cleaned_data.get("song_title"):
                    context = {
                        'album': album,
                        'form': form,
                        'error_message': 'You already added that song',
                        'username': username
                    }
                    return render(request, 'music/create_song.html', context)
            song = form.save(commit=False)
            song.album = album
            song.song_file = request.FILES['song_file']
            file_type = song.song_file.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in AUDIO_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Audio file must be WAV, MP3, or OGG',
                    'username': username
                }
                return render(request, 'music/create_song.html', context)

            song.save()
            return render(request, 'music/detail.html', {'album': album,
                'username': username })
        context = {
            'album': album,
            'form': form,
            'username': username
        }
        return render(request, 'music/create_song.html', context)
		

def play_song(request, album_id, song_id): 
    if request.user.is_authenticated():
        username = request.user.get_short_name()
    else: 
        username= None
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    return render(request, 'music/play_audio.html', 
        {'song': song ,'album': album, 'username': username })

def delete_song(request, album_id, song_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html', {'error_message': 
            'Need to Login'} )
    elif not request.user.is_staff: 
        return render(request, 'music/login.html', {'error_message': 
            'Only Admin can delete Song'} )
    else:
    	album = get_object_or_404(Album, pk=album_id)
    	song = Song.objects.get(pk=song_id)
    	song.delete()
    	return render(request, 'music/detail.html', {'album': album})

def favorite(request, song_id, album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html', {'error_message': 
            'Need to Login'} )
    else:
        username = request.user.get_short_name()
        album = get_object_or_404(Album, pk=album_id)
        song = get_object_or_404(Song, pk=song_id)
        try:
            if song.is_favorite:
                song.is_favorite = False
            else:
                song.is_favorite = True
            song.save()
        except (KeyError, Song.DoesNotExist):
            return JsonResponse({'success': False})
        album = Album.objects.get(pk=album_id)
        return render(request , 'music/detail.html', 
            {'album': album,'username': username } )


def songs(request, filter_by):
    if not request.user.is_authenticated():
        username = None
    else: username = request.user.get_short_name()
    try:
        song_ids = []
        for album in Album.objects.all():
            for song in album.song_set.all():
                song_ids.append(song.pk)
        users_songs = Song.objects.filter(pk__in=song_ids)
        if filter_by == 'favorites':
            users_songs = users_songs.filter(is_favorite=True)
    except Album.DoesNotExist:
        users_songs = []
    return render(request, 'music/songs.html', {
        'song_list': users_songs,
        'filter_by': filter_by,
        'username': username,
    })

website/views.py
from music import views

from django.shortcuts import render, redirect , get_object_or_404


def index(request):
	return redirect('music:index')

website/templates/music/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<link rel="shortcut icon" type="image/png" href="{% static 'music/favicon.ico' %}"/>
		<meta charset="utf-8">
		<title>{% block title %}Picric{% endblock %}</title>
		<meta name="description" content="">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
	</head>
	<body>
		<nav class="navbar navbar-inverse ">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=#topNavBar>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'music:index' %}">Picric</a>
				</div>
				<div class="collapse navbar-collapse" id="topNavBar">
					<ul class="nav navbar-nav">
						<li class="{% block albums_active %}{% endblock %}">
							<a href="{% url 'music:index' %}">
								<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
								Albums
							</a>
						</li>
						<li class="{% block songs_active %}{% endblock %}">
							<a href="{% url 'music:songs' 'all' %}">
								<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
								Songs
							</a>
						</li>
					</ul>
					<form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
						<div class="form-group">
							<input type="text" name="q" value="" class="form-control">
						</div>
						<button type="submit" class="btn btn-default">Search</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						{% if username %}
						<li class="{% block add_album %}{% endblock %}">
							<a href="{% url 'music:album-add' %}">
								<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
								Add Album
							</a>
						</li>
						{% endif %}
						{% if not username %}
						<li class="{% block register_active %}{% endblock %}">
							<a href="{% url 'music:register' %}">
							<span class="glyphicon glyphicon-plus-sign" aria-hidden="true">	
							</span>&nbsp;
								Signup
							</a>
						</li>
						<li class="{% block login_active %}{% endblock %}">
							<a href="{% url 'music:login_user' %}">
							<span class="glyphicon glyphicon-off" aria-hidden="true">	
							</span>&nbsp;
								Login
							</a>
						</li>
						{% else %}
						<li class="">
							<a href="{% url 'music:logout_user' %}">
							<span class="glyphicon glyphicon-off" aria-hidden="true">	
							</span>&nbsp;
								{{ username }}|Logout
							</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
		{% block body %}
		{% endblock %}
	</body>
</html>

website/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3 z-depth-1">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

<div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active hoverable"><a href="{% url 'music:index' %}">View All</a></li>
                {% if username %}
                <li role="presentation" class="active hoverable"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
                {% endif %}
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{% url 'music:play_song' album.id song.id %}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'music:favorite' album.id song.id %}" class="btn-favorite"><span class="{% if song.is_favorite %} glyphicon glyphicon-heart {% else %} glyphicon glyphicon-star {% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>


{% endblock %}

website/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

website/templates/music/play_audio.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <link rel="shortcut icon" type="image/png" href="{% static 'music/favicon.ico' %}"/>
    <title>{% block title %}Picric{% endblock %}</title>
    <meta name="description" content="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.1.1/css/mdb.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.1.1/js/mdb.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <meta charset="utf-8" />
    <title>My Audio Player</title>
    <link href="{% static 'music/dist/skin/blue.monday/css/jplayer.blue.monday.min.css' %}" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="{% static 'music/lib/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'music/dist/jplayer/jquery.jplayer.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'music/dist/add-on/jplayer.playlist.min.js' %}"></script>
    <script type="text/javascript">
    //<![CDATA[
    $(document).ready(function(){

      new jPlayerPlaylist({
        jPlayer: "#jquery_jplayer_1",
        cssSelectorAncestor: "#jp_container_1"
      }, [
      {% for song in album.song_set.all %}
        {
          title:"{{ song.song_title }}",
          artist:"{{ album.artist }}",
          mp3:"{{ song.song_file.url }}",
          oga:"{{ song.song_file.url }}",
          poster: "{{ album.album_logo.url }}"
        },
      {% endfor %}
      ], {
        swfPath: "../../dist/jplayer",
        supplied: "webmv, ogv, m4v, oga, mp3",
        useStateClassSkin: true,
        autoBlur: false,
        smoothPlayBar: true,
        keyEnabled: true,
        audioFullScreen: true
      });
    });
    //]]>
    </script>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=#topNavBar>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'music:index' %}">Picric</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="{% block albums_active %}{% endblock %}">
              <a href="{% url 'music:index' %}">
                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                Albums
              </a>
            </li>
            <li class="{% block songs_active %}{% endblock %}">
              <a href="{% url 'music:songs' 'all' %}">
                <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                Songs
              </a>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
            <div class="form-group">
              <input type="text" name="q" value="" class="form-control">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            {% if username %}
            <li class="{% block add_album %}{% endblock %}">
              <a href="{% url 'music:album-add' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                Add Album
              </a>
            </li>
            {% endif %}
            {% if not username %}
            <li class="{% block register_active %}{% endblock %}">
              <a href="{% url 'music:register' %}">
              <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"> 
              </span>&nbsp;
                Signup
              </a>
            </li>
            <li class="{% block login_active %}{% endblock %}">
              <a href="{% url 'music:login_user' %}">
              <span class="glyphicon glyphicon-off" aria-hidden="true"> 
              </span>&nbsp;
                Login
              </a>
            </li>
            {% else %}
            <li class="">
              <a href="{% url 'music:logout_user' %}">
              <span class="glyphicon glyphicon-off" aria-hidden="true"> 
              </span>&nbsp;
                {{ username }}|Logout
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div id="jp_container_1" class="jp-video jp-video-270p centre" role="application" aria-label="media player">
  <div class="jp-type-playlist">
    <div id="jquery_jplayer_1" class="jp-jplayer"></div>
    <div class="jp-gui">
      <div class="jp-video-play">
        <button class="jp-video-play-icon" role="button" tabindex="0">play</button>
      </div>
      <div class="jp-interface">
        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>
        <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
        <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
        <div class="jp-controls-holder">
          <div class="jp-controls">
            <button class="jp-previous" role="button" tabindex="0">previous</button>
            <button class="jp-play" role="button" tabindex="0">play</button>
            <button class="jp-next" role="button" tabindex="0">next</button>
            <button class="jp-stop" role="button" tabindex="0">stop</button>
          </div>
          <div class="jp-volume-controls">
            <button class="jp-mute" role="button" tabindex="0">mute</button>
            <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
            <div class="jp-volume-bar">
              <div class="jp-volume-bar-value"></div>
            </div>
          </div>
          <div class="jp-toggles">
            <button class="jp-repeat" role="button" tabindex="0">repeat</button>
            <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
            <button class="jp-full-screen" role="button" tabindex="0">full screen</button>
          </div>
        </div>
        <div class="jp-details">
          <div class="jp-title" aria-label="title">&nbsp;</div>
        </div>
      </div>
    </div>
    <div class="jp-playlist">
      <ul>
        <!-- The method Playlist.displayPlaylist() uses this unordered list -->
        <li>&nbsp;</li>
      </ul>
    </div>
    <div class="jp-no-solution">
      <span>Update Required</span>
      To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
    </div>
  </div>
</div>
  </body>

</html>

website/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Create New User{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New User</h3>
                    {% if error_message %}
                        <p class="text-danger small">{{ error_message }}</p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            <div class="panel-footer">Have an account? <a href="{% url 'music:login_user' %}">Click here</a> to Login.
            </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

website/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a class="hoverable" href="{% url 'music:songs' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a class=" hoverable " href="{% url 'music:songs' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{% url 'music:play_song' song.album.id song.id %}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a class="my_album_title" href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.album.id song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}